package main.helper;

public enum ImageType {
  WHITE_PAWN,
  WHITE_ROOK,
  WHITE_BISHOP,
  WHITE_KNIGHT,
  WHITE_QUEEN,
  WHITE_KING,
  BLACK_PAWN,
  BLACK_ROOK,
  BLACK_BISHOP,
  BLACK_KNIGHT,
  BLACK_QUEEN,
  BLACK_KING,
  DARK_TILE,
  LIGHT_TILE,
  DARK_TILE_HIGHLIGHTED,
  LIGHT_TILE_HIGHLIGHTED
}
